version: '3.8'

services:
  cube:
    build: .
    ports:
      - "4000:4000"
    restart: on-failure
    env_file: .env
    environment:
      CUBEJS_DB_HOST: host.docker.internal
      CUBEJS_DB_NAME: dev
      CUBEJS_DB_PORT: 3306
      CUBEJS_DB_USER: root
      CUBEJS_DB_PASS: rootpasswrod
      # CUBEJS_CACHE_AND_QUEUE_DRIVER: cubestore

      # REDIS_URL: redis://redis:6379
    volumes:
      - .:/cube/conf
    networks:
      - backend_default
  redis:
    image: redis:6
    restart: always
    # ports:
    #   - "6379:6379"
  externalDb:
    image: mysql:8.4.3
    command: "--mysql-native-password=ON"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev
    ports:
      - 3307:3306
    networks:
      - backend_default
networks:
  backend_default:
    external: true
